Repository Maggie-Sarmiento/Burger-queen, pull requests merged in 2022-05, with the labels that each got.

#5 conection with firebase and Login in firebase
  package-lock.json
  package.json
  src/App.jsx
  src/Authenticate/Staff.jsx
  src/Firebase/firebase.config.js
  src/No-Authenticate/LogIn.jsx
  src/No-Authenticate/Login/LogIn.jsx
  src/No-Authenticate/Login/Login.module.css
Labels: prioridad: alta

#7 create components of admin
  src/App.jsx
  src/Authenticate/Staff.jsx
  src/Authenticate/Staff.module.css
  src/No-Authenticate/Login/LogIn.jsx
  src/No-Authenticate/NotFound.jsx
  src/Sidebar.jsx
  src/Sidebar.module.css
Labels: priority: medium

#8 Firebase roles
  src/App.jsx
  src/Authenticate/Staff.jsx
  src/Firebase/firebase.config.js
  src/No-Authenticate/Login/Login.module.css
  src/Sidebar.module.css
  src/index.css
Labels: priority: medium

#11 Create Header and component Log out
  .eslintrc.json
  package-lock.json
  package.json
  src/App.jsx
  src/Authenticate/Components/Header.jsx
  src/Authenticate/Components/Header.module.css
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/Profile.jsx
  src/Authenticate/Components/Profile.module.css
  src/Authenticate/Components/Sidebar.jsx
  src/Authenticate/Components/Sidebar.module.css
  src/Authenticate/Staff.jsx
  src/Authenticate/Staff.module.css
  src/No-Authenticate/NotFound.jsx
  src/Sidebar.jsx
Labels: priority: low

#13 Create register of profile
  src/App.jsx
  src/Authenticate/Components/ModalStaff.jsx
  src/No-Authenticate/Login/LogIn.jsx
Labels: priority: medium

#17 Create render conditional for Admin, Waiter and Chef
  src/App.jsx
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/Sidebar.jsx
  src/Authenticate/Staff.jsx
  src/Authenticate/views/Admin.jsx
  src/Authenticate/views/Admin.module.css
  src/Authenticate/views/Chef.jsx
  src/Authenticate/views/Chef.module.css
  src/Authenticate/views/Waiter.jsx
  src/Authenticate/views/Waiter.module.css
  src/No-Authenticate/Login/LogIn.jsx
  src/reportWebVitals.js
Labels: priority: high

#19 create table of staff on Admin/Staff
  db.json
  package-lock.json
  package.json
  src/App.jsx
  src/Authenticate/Components/Header.jsx
  src/Authenticate/Components/Header.module.css
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/ModalStaff.module.css
  src/Authenticate/Components/Profile.jsx
  src/Authenticate/Components/Sidebar.module.css
  src/Authenticate/views/Admin.jsx
  src/Authenticate/views/Admin.module.css
  src/Authenticate/views/Staff.jsx
  src/Authenticate/views/Staff.module.css
  src/Authenticate/views/Waiter.jsx
Labels: priority: high

#21 Create the create and read on table admin
  db.json
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/views/Staff.jsx
Labels: priority: medium

#22 create render conditional on admin
  db.json
  src/App.jsx
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/Sidebar.jsx
  src/Authenticate/Subviews/MenuAlmuerzo.jsx
  src/Authenticate/Subviews/MenuDesayuno.jsx
  src/Authenticate/views/Admin.jsx
  src/Authenticate/views/Chef.jsx
  src/Authenticate/views/Waiter.jsx
  src/PrivateRoute.jsx
Labels: priority: medium

#25 Feature/create conditional admin
  db.json
  src/App.jsx
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/StaffBtn.jsx
  src/Authenticate/views/Staff.jsx
  src/Authenticate/views/Staff.module.css
  src/Authenticate/views/Waiter.jsx
  src/No-Authenticate/Login/LogIn.jsx
Labels: priority: medium

#27 Feature/feature/create conditional admin crud
  db.json
  src/App.jsx
  src/Authenticate/Components/Header.jsx
  src/Authenticate/Components/ModalStaff.jsx
  src/Authenticate/Components/Profile.jsx
  src/Authenticate/Components/Sidebar.module.css
  src/Authenticate/Components/StaffBtn.jsx
  src/Authenticate/views/Admin.jsx
  src/Authenticate/views/Admin.module.css
  src/Authenticate/views/Staff.jsx
  src/Authenticate/views/Staff.module.css
  src/No-Authenticate/Login/LogIn.jsx
  src/PrivateRoute.jsx
  src/index.jsx
  src/reportWebVitals.js
Labels: priority: medium

#28 Create CRUD Admin
  db.json
  src/App.jsx
  src/Authenticate/views/Staff.jsx
  src/Firebase/firebase.config.js
  src/No-Authenticate/Login/LogIn.jsx
Labels: priority: medium

#30 Create subview admin menu
  db.json
  src/Authenticate/Components/CardMenu.jsx
  src/Authenticate/Components/CardMenu.module.css
  src/Authenticate/Components/CardMenuLunch.jsx
  src/Authenticate/Components/CardMenuLunch.module.css
  src/Authenticate/Components/Profile.jsx
  src/Authenticate/Components/Sidebar.jsx
  src/Authenticate/Subcomponents/MenuBtn.jsx
  src/Authenticate/Subcomponents/ModalMenu.jsx
  src/Authenticate/Subviews/Menu.jsx
  src/Authenticate/Subviews/MenuAlmuerzo.jsx
  src/Authenticate/Subviews/MenuDesayuno.jsx
  src/Authenticate/Subviews/MenuLunch.jsx
  src/Firebase/firebase.config.js
  src/PrivateRoute.jsx
Labels: priority: medium

#32 Create modal menu on Mmenu of admin subview
  db.json
  src/Authenticate/Subcomponents/CardMenu.jsx
  src/Authenticate/Subcomponents/CardMenu.module.css
  src/Authenticate/Subcomponents/CardMenuLunch.jsx
  src/Authenticate/Subcomponents/CardMenuLunch.module.css
  src/Authenticate/Subcomponents/MenuBtn.jsx
  src/Authenticate/Subcomponents/ModalMenu.jsx
  src/Authenticate/Subcomponents/ModalMenu.module.css
  src/Authenticate/Subviews/Menu.jsx
  src/Authenticate/Subviews/MenuLunch.jsx
Labels: priority: medium

#33 Feature/options products
  src/Authenticate/Subcomponents/CardMenu.jsx
  src/Authenticate/Subcomponents/CardMenu.module.css
  src/Authenticate/Subcomponents/ThreeDotsMenu.jsx
  src/Firebase/firebase.config.js
Labels: priority: low

#36 create cru admin menu
  db.json
  src/Authenticate/Subcomponents/CardMenu.jsx
  src/Authenticate/Subcomponents/ModalEditMenu.jsx
  src/Authenticate/Subcomponents/ThreeDotsMenu.jsx
Labels: priority: medium

#37 Feature/delete menu item
  db.json
  src/Authenticate/Subcomponents/ModalDeleteMenu.jsx
  src/Authenticate/Subcomponents/ThreeDotsMenu.jsx
Labels: priority: medium

#41 Feature/crud admin menus
  db.json
  package-lock.json
  package.json
  src/App.jsx
  src/App.test.js
  src/App.test.jsx
  src/Authenticate/Subcomponents/CardMenu.module.css
  src/Components/Authenticate/Admin/Admin.jsx
  src/Components/Authenticate/Admin/Admin.module.css
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.jsx
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.module.css
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.module.css
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.module.css
  src/Components/Authenticate/Admin/Menu/MenuBtn.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalEditMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu.module.css
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu.jsx
  src/Components/Authenticate/Admin/Staff/ModalStaff.jsx
  src/Components/Authenticate/Admin/Staff/ModalStaff.module.css
  src/Components/Authenticate/Admin/Staff/Staff.jsx
  src/Components/Authenticate/Admin/Staff/Staff.module.css
  src/Components/Authenticate/Admin/Staff/StaffBtn.jsx
  src/Components/Authenticate/Chef/Chef.jsx
  src/Components/Authenticate/Chef/Chef.module.css
  src/Components/Authenticate/Common/Header.jsx
  src/Components/Authenticate/Common/Header.module.css
  src/Components/Authenticate/Common/Profile.jsx
  src/Components/Authenticate/Common/Profile.module.css
  src/Components/Authenticate/Common/Sidebar.jsx
  src/Components/Authenticate/Common/Sidebar.module.css
  src/Components/Authenticate/Waiter/Waiter.jsx
  src/Components/Authenticate/Waiter/Waiter.module.css
  src/Components/No-Authenticate/Login/LogIn.jsx
  src/Components/No-Authenticate/Login/Login.module.css
  src/Components/No-Authenticate/NotFound.jsx
  src/PrivateRoute.jsx
  src/__snapshots__/App.test.jsx.snap
Labels: priority: medium

#43 Feature/create menu lunch
  .eslintignore
  db.json
  src/App.jsx
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.jsx
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.module.css
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalEditMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu.jsx
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu.jsx
  src/Components/Authenticate/Common/Profile.jsx
Labels: priority: medium

#44 Feature/fix cardmenu txt
  db.json
  src/Components/Authenticate/Admin/Admin.jsx
  src/Components/Authenticate/Admin/Admin.module.css
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.jsx
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.module.css
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.module.css
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.module.css
  src/Components/Authenticate/Admin/Menu/ModalMenu.jsx
  src/Components/Authenticate/Admin/Staff/Staff.module.css
  src/Components/Authenticate/Common/Header.jsx
  src/Components/Authenticate/Common/Header.module.css
  src/Components/Authenticate/Common/Sidebar.jsx
  src/Components/Authenticate/Common/Sidebar.module.css
Labels: priority: low

#48 Ingresar al sistema de pedidos.
  src/Components/Authenticate/Admin/Admin.module.css
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/BtnAdd.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Common/Header.jsx
  src/Components/Authenticate/Common/ShoppingCar.jsx
  src/Components/Authenticate/Common/Sidebar.jsx
  src/Components/Authenticate/Waiter/Waiter.jsx
  src/Components/Authenticate/Waiter/Waiter.module.css
  src/Components/No-Authenticate/Login/LogIn.jsx
  src/PrivateRoute.jsx
Labels: priority: medium

#53 Feature/waiter shopping cart
  db.json
  src/Components/Authenticate/Admin/Admin.module.css
  src/Components/Authenticate/Admin/Menu/BtnAdd.jsx
  src/Components/Authenticate/Admin/Staff/Staff.jsx
  src/Components/Authenticate/Common/Header.jsx
  src/Components/Authenticate/Common/ShoppingCar.jsx
  src/Components/Authenticate/Waiter/ShoppingCar.jsx
  src/Components/Authenticate/Waiter/Waiter.jsx
Labels: priority: medium

#57 Feature/view chef
  db.json
  src/Components/Authenticate/Admin/Admin.jsx
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.jsx
  src/Components/Authenticate/Admin/LunchMenu/CardMenuLunch.module.css
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.module.css
  src/Components/Authenticate/Chef/BtnAddServe.jsx
  src/Components/Authenticate/Chef/CardOrder.jsx
  src/Components/Authenticate/Chef/Chef.jsx
  src/Components/Authenticate/Chef/Chef.module.css
  src/Components/Authenticate/Chef/Orders.jsx
  src/Components/Authenticate/Common/Home.jsx
  src/Components/Authenticate/Common/Home.module.css
  src/Components/Authenticate/Waiter/ShoppingCar.jsx
  src/Components/Authenticate/Waiter/Waiter.jsx
  src/Components/Authenticate/Waiter/Waiter.module.css
  src/Components/No-Authenticate/Login/LogIn.jsx
  src/PrivateRoute.jsx
Labels: priority: high

#60 Feature/view chef timer
  db.json
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalEditMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu.jsx
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu.jsx
  src/Components/Authenticate/Admin/Staff/Staff.jsx
  src/Components/Authenticate/Chef/BtnAddServe.jsx
  src/Components/Authenticate/Chef/CardOrder.jsx
  src/Components/Authenticate/Chef/Orders.jsx
  src/Components/Authenticate/Common/Header.jsx
  src/Components/Authenticate/Waiter/BtnAddCheckService.jsx
  src/Components/Authenticate/Waiter/CardServeOrder.jsx
  src/Components/Authenticate/Waiter/ListOrders.jsx
  src/Components/Authenticate/Waiter/ServeOrders.jsx
  src/Components/Authenticate/Waiter/ShoppingCar.jsx
Labels: priority: medium

#64 Home welcome
  db.json
  public/waiter.jpg
  public/yellowspot.jpg
  src/Components/Authenticate/Chef/BtnAddServe.jsx
  src/Components/Authenticate/Chef/CardOrder.jsx
  src/Components/Authenticate/Common/Home.jsx
  src/Components/Authenticate/Common/Home.module.css
  src/Components/Authenticate/Common/Welcome.jsx
  src/Components/Authenticate/Common/Welcome.module.css
  src/Components/Authenticate/Waiter/BtnAddCheckService.jsx
  src/Components/Authenticate/Waiter/CardServeOrder.jsx
Labels: priority: low

#65 styles on home and check responsive web design on proyect
  src/Components/Authenticate/Common/Profile.jsx
  src/Components/Authenticate/Common/Sidebar.jsx
  src/Components/Authenticate/Common/Sidebar.module.css
  src/Components/Authenticate/Common/Welcome.jsx
  src/Components/Authenticate/Common/Welcome.module.css
  src/Components/Authenticate/Waiter/ListOrders.jsx
  src/Components/Authenticate/Waiter/ListOrders.module.css
  src/Components/Authenticate/Waiter/ShoppingCar.jsx
  src/index.css
Labels: priority: low

#68 Test Integration to file common
  package-lock.json
  package.json
  src/App.jsx
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.test.jsx
  src/Components/Authenticate/Admin/LunchMenu/__snapshots__/MenuLunch.test.jsx.snap
  src/Components/Authenticate/Common/Header/Header.jsx
  src/Components/Authenticate/Common/Header/Header.module.css
  src/Components/Authenticate/Common/Header/Header.test.jsx
  src/Components/Authenticate/Common/Header/__snapshots__/Header.test.jsx.snap
  src/Components/Authenticate/Common/Home/Home.jsx
  src/Components/Authenticate/Common/Home/Home.module.css
  src/Components/Authenticate/Common/Home/Home.test.jsx
  src/Components/Authenticate/Common/Home/__snapshots__/Home.test.jsx.snap
  src/Components/Authenticate/Common/Profile/Profile.jsx
  src/Components/Authenticate/Common/Profile/Profile.module.css
  src/Components/Authenticate/Common/Profile/Profile.test.jsx
  src/Components/Authenticate/Common/Profile/__snapshots__/Profile.test.jsx.snap
  src/Components/Authenticate/Common/Sidebar/Sidebar.jsx
  src/Components/Authenticate/Common/Sidebar/Sidebar.module.css
  src/Components/Authenticate/Common/Sidebar/Sidebar.test.jsx
  src/Components/Authenticate/Common/Sidebar/__snapshots__/Sidebar.test.jsx.snap
  src/Components/Authenticate/Common/Welcome/Welcome.jsx
  src/Components/Authenticate/Common/Welcome/Welcome.module.css
  src/Components/Authenticate/Common/Welcome/Welcome.test.jsx
  src/Components/Authenticate/Common/Welcome/__snapshots__/Welcome.test.jsx.snap
  src/Components/No-Authenticate/NotFound/NotFound.jsx
  src/Components/No-Authenticate/NotFound/NotFound.test.js
  src/Components/No-Authenticate/NotFound/__snapshots__/NotFound.test.js.snap
  src/PrivateRoute.jsx
  src/PrivateRoute.test.jsx
  src/__snapshots__/PrivateRoute.test.jsx.snap
  src/index.test.jsx
Labels: priority: medium

#69 Feature/read me
  README.md
  db.json
  public/BQlogo.png
  public/prototipos.png
Labels: priority: low

#74 update Readme
  README.md
  db.json
Labels: priority: low

#76 integration test on chef and waiter
  src/Components/Authenticate/Admin/Staff/Staff.test.jsx
  src/Components/Authenticate/Admin/Staff/__snapshots__/Staff.test.jsx.snap
  src/Components/Authenticate/Chef/BtnAddServe/BtnAddServe.jsx
  src/Components/Authenticate/Chef/BtnAddServe/BtnAddServe.test.jsx
  src/Components/Authenticate/Chef/BtnAddServe/__snapshots__/BtnAddServe.test.jsx.snap
  src/Components/Authenticate/Chef/CardOrder.test.jsx
  src/Components/Authenticate/Chef/CardOrder/CardOrder.jsx
  src/Components/Authenticate/Chef/CardOrder/CardOrder.test.jsx
  src/Components/Authenticate/Chef/CardOrder/__snapshots__/CardOrder.test.jsx.snap
  src/Components/Authenticate/Chef/Orders/Orders.jsx
  src/Components/Authenticate/Chef/Orders/Orders.test.jsx
  src/Components/Authenticate/Chef/Orders/__snapshots__/Orders.test.jsx.snap
  src/Components/Authenticate/Common/Header/Header.jsx
  src/Components/Authenticate/Waiter/BtnAddCheckService/BtnAddCheckService.jsx
  src/Components/Authenticate/Waiter/BtnAddCheckService/BtnAddCheckService.test.jsx
  src/Components/Authenticate/Waiter/BtnAddCheckService/__snapshots__/BtnAddCheckService.test.jsx.snap
  src/Components/Authenticate/Waiter/CardServeOder/CardServeOrder.jsx
  src/Components/Authenticate/Waiter/CardServeOder/CardServeOrder.test.jsx
  src/Components/Authenticate/Waiter/CardServeOder/__snapshots__/CardServeOrder.test.jsx.snap
  src/Components/Authenticate/Waiter/CardServeOrder.jsx
  src/Components/Authenticate/Waiter/ListOrders/ListOrders.jsx
  src/Components/Authenticate/Waiter/ListOrders/ListOrders.module.css
  src/Components/Authenticate/Waiter/ListOrders/ListOrders.test.jsx
  src/Components/Authenticate/Waiter/ListOrders/__snapshots__/ListOrders.test.jsx.snap
  src/Components/Authenticate/Waiter/ServeOrders/ServeOrder.test.jsx
  src/Components/Authenticate/Waiter/ServeOrders/ServeOrders.jsx
  src/Components/Authenticate/Waiter/ServeOrders/__snapshots__/ServeOrder.test.jsx.snap
  src/Components/Authenticate/Waiter/ShoppingCar/ShoppingCar.jsx
  src/Components/Authenticate/Waiter/ShoppingCar/ShoppingCar.test.jsx
  src/Components/Authenticate/Waiter/ShoppingCar/__snapshots__/ShoppingCar.test.jsx.snap
  src/PrivateRoute.jsx
Labels: priority: medium

#77 Developer test unitario
  src/Components/Authenticate/Admin/LunchMenu/MenuLunch.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu/CardMenu.jsx
  src/Components/Authenticate/Admin/Menu/CardMenu/CardMenu.module.css
  src/Components/Authenticate/Admin/Menu/Menu.jsx
  src/Components/Authenticate/Admin/Menu/Menu.test.jsx
  src/Components/Authenticate/Admin/Menu/MenuBtn/MenuBtn.jsx
  src/Components/Authenticate/Admin/Menu/MenuBtn/MenuBtn.test.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/ModalDeleteMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/ModalDeleteMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/ModalEditMenu/ModalEditMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalEditMenu/ModalEditMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu/ModalMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu/ModalMenu.module.css
  src/Components/Authenticate/Admin/Menu/ModalMenu/ModalMenu.test.js
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu/ThreeDotsMenu.jsx
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu/ThreeDotsMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/__snapshots__/Menu.test.js.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/Menu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/MenuBtn.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/ModalDeleteMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/ModalEditMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/ModalMenu.test.js.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/ThreeDotsMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Staff/ModalStaff/ModalStaff.jsx
  src/Components/Authenticate/Admin/Staff/ModalStaff/ModalStaff.module.css
  src/Components/Authenticate/Admin/Staff/ModalStaff/ModalStaff.test.jsx
  src/Components/Authenticate/Admin/Staff/Staff.jsx
  src/Components/Authenticate/Admin/Staff/__snapshots__/ModalStaff.test.jsx.snap
  src/Components/Authenticate/Chef/CardOrder/CardOrder.jsx
  src/Components/Authenticate/Common/Profile/Profile.jsx
  src/Components/Authenticate/Common/Profile/Profile.test.jsx
  src/Components/Authenticate/Waiter/CardServeOder/CardServeOrder.jsx
Labels: priority: low

#79 create test on shopping car of handleClick and handleCancel
  src/Components/Authenticate/Admin/Menu/MenuBtn/__snapshots__/MenuBtn.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/__snapshots__/ModalDeleteMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/ModalEditMenu/__snapshots__/ModalEditMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/ModalMenu/ModalMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/ModalMenu/__snapshots__/ModalMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu/__snapshots__/ThreeDotsMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/__snapshots__/Menu.test.js.snap
  src/Components/Authenticate/Admin/Staff/ModalStaff/__snapshots__/ModalStaff.test.jsx.snap
  src/Components/Authenticate/Waiter/ShoppingCar/ShoppingCar.jsx
  src/Components/Authenticate/Waiter/ShoppingCar/ShoppingCar.test.jsx
Labels: priority: low

#81 Test unitarios to file
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/ModalDeleteMenu.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/ModalDeleteMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/ModalDeleteMenu/__snapshots__/ModalDeleteMenu.test.jsx.snap
  src/Components/Authenticate/Admin/Menu/ModalEditMenu/ModalEditMenu.test.jsx
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu/ThreeDotsMenu.jsx
  src/Components/Authenticate/Admin/Menu/ThreeDotsMenu/ThreeDotsMenu.test.jsx
  src/Components/Authenticate/Admin/Staff/ModalStaff/ModalStaff.jsx
  src/Components/Authenticate/Admin/Staff/ModalStaff/ModalStaff.test.jsx
  src/Components/Authenticate/Common/Header/Header.test.jsx
  src/Components/Authenticate/Common/Home/Home.test.jsx
  src/Components/Authenticate/Common/Profile/Profile.jsx
  src/Components/Authenticate/Common/Profile/Profile.test.jsx
  src/Components/Authenticate/Common/Sidebar/Sidebar.jsx
  src/Components/Authenticate/Common/Sidebar/Sidebar.test.jsx
  src/PrivateRoute.test.jsx
  src/__snapshots__/PrivateRoute.test.jsx.snap
Labels: priority: medium

#82 Unit test
  db.json
  package-lock.json
  src/App.jsx
  src/Components/Authenticate/Common/Home/Home.jsx
  src/Components/Authenticate/Common/Profile/Profile.jsx
  src/Components/No-Authenticate/Login/LogIn.jsx
  src/Components/No-Authenticate/Login/Login.test.jsx
  src/Firebase/__mocks__/firebase.config.js
  src/Firebase/firebase.config.js
Labels: priority: low

#83 changes in file profile
  src/Components/Authenticate/Common/Profile/Profile.jsx
  src/Components/Authenticate/Common/Profile/Profile.test.jsx
Labels: priority: low
